apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: ingress-takaaki-f5
spec:
  host: takaaki-f5.xyz
  tls:
    secret: cafe-secret
  upstreams:
  - name: nginx-f5
    service: nginx-f5-svc
    port: 80
    healthCheck:
      enable: true
      path: /
  routes:
  - path: /
    policies:
    - name: maintenance-policy-2021
    action:
      pass: nginx-f5
    errorPages:
    - codes: [403]
      redirect:
        code: 302
        url: https://nginx.org
